twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        rpc_client: '@App\RpcBitcoin\Client'

when@test:
    twig:
        strict_variables: true
